/**
 * Official Poshmark create-listing style tag suggestions.
 * Sourced from https://poshmark.com/api/meta/style_tags (Aug 2026).
 * Sellers may pick up to 3 per listing.
 */
export const POSHMARK_STYLE_TAGS = [
  "70s",
  "80s",
  "90s",
  "Abstract",
  "Academia",
  "Acrylic",
  "Activewear",
  "A-Line",
  "Animal Print",
  "Art Deco",
  "Asymmetrical",
  "Athleisure",
  "Athletic",
  "Avant Garde",
  "Awards Season",
  "Aztec",
  "Baggy",
  "Balletcore",
  "Barbie",
  "Barbiecore",
  "Beach",
  "Beaded",
  "Biker",
  "Bikercore",
  "Black Tie",
  "Blokecore",
  "Bodycon",
  "Bohemian",
  "Bollywood",
  "Bootcut",
  "Bow",
  "Boyfriend",
  "Brass",
  "Breathable",
  "Bridal",
  "Bridesmaid",
  "Brocade",
  "Business Casual",
  "Cable Knit",
  "California",
  "Camo",
  "Cargo",
  "Cashmere",
  "Casual",
  "Celeb Style",
  "Celtic",
  "Ceramic",
  "Checks",
  "Chevron",
  "Christmas",
  "Chunky",
  "Cinched",
  "Classic",
  "Clean Beauty",
  "Coastal",
  "Coastal Cowgirl",
  "Coastal Grandma",
  "Cocktail",
  "Collectible",
  "Collegiate",
  "Colorblock",
  "Colorful",
  "Comfy",
  "Contemporary",
  "Coord Sets",
  "Copper",
  "Coquette Girl",
  "Corduroy",
  "Cosplay",
  "Cottagecore",
  "Cotton",
  "Cozy",
  "Craftsman",
  "Crochet",
  "Cropped",
  "Cruelty-Free",
  "Crystal",
  "Cut Out",
  "Dainty",
  "Denim",
  "Designer",
  "Disco",
  "Disney",
  "Distressed",
  "DIY",
  "Dorm Ready",
  "Dots",
  "Drop Waist",
  "Earthenware",
  "Eclectic",
  "Eclectic Grandpa",
  "Embroidered",
  "Empire Waist",
  "Equestrian",
  "Ethnic",
  "Evening",
  "Fall",
  "Fandom",
  "Farmhouse",
  "Faux Fur",
  "Faux Leather",
  "Feminine",
  "Festival",
  "Festive",
  "Fit & Flare",
  "Fitted",
  "Flannel",
  "Flare",
  "Fleece",
  "Floral",
  "Flowy",
  "Folk Art",
  "Formal",
  "Fragrance-Free",
  "French",
  "Fringe",
  "Fur",
  "Gifts",
  "Gingham",
  "Girlhoodcore",
  "Glass",
  "Gold",
  "Golf",
  "Gorpcore",
  "Goth",
  "Greek Key",
  "Grunge",
  "Gym",
  "Halter",
  "Hand Knit",
  "Handmade",
  "Hanukkah",
  "Harry Potter",
  "Hawaiian",
  "Hello Kitty",
  "Hemp",
  "Herringbone",
  "High Waist",
  "Hiking",
  "Hippie",
  "Holiday",
  "Houndstooth",
  "Indie Sleeze",
  "Industrial",
  "Jacquard",
  "Jewel Tone",
  "Kawaii",
  "Keyhole",
  "Knit",
  "Lace",
  "Lace up",
  "Leather",
  "Leopard Print",
  "Lightweight",
  "Limited Edition",
  "Linen",
  "Lolita",
  "Loose Fit",
  "Loungewear",
  "Lucite",
  "Luxury",
  "Mad Max",
  "Madras",
  "Marvel",
  "Matte",
  "Maximalism",
  "Mediterranean",
  "Mermaidcore",
  "Mesh",
  "Metal",
  "Metallic",
  "Mid-Century Modern",
  "Midi",
  "Military",
  "Mini",
  "Minimalist",
  "Mobwife",
  "Mod",
  "Modest",
  "Monochrome",
  "Monogram",
  "Moto",
  "Nautical",
  "Neon",
  "Netflix Shop",
  "Neutral",
  "Nylon",
  "Off the Shoulder",
  "Office",
  "Oil-Free",
  "Olympics",
  "One shoulder",
  "Outdoor",
  "Oversized",
  "Paisley",
  "Paraben-Free",
  "Party",
  "Pastel",
  "Patchwork",
  "Peanuts",
  "Peasant",
  "Peplum",
  "Performance Wear",
  "Plaid",
  "Platform",
  "Pleated",
  "Pokemon",
  "Polka Dot",
  "Polyester",
  "Pop Art",
  "Porcelain",
  "Preppy",
  "Prom",
  "Punk",
  "Quiet Luxury",
  "Quilted",
  "Rainbow",
  "Red Carpet",
  "Relaxed Fit",
  "Reptile",
  "Resin",
  "Resortwear",
  "Retro",
  "Ribbed",
  "Romper",
  "Rosette",
  "Ruffle",
  "Running",
  "Rustic",
  "Sailor",
  "Satin",
  "Scandinavian",
  "Seersucker",
  "Sequins",
  "Shabby Chic",
  "Sheath",
  "Sheer",
  "Sherpa",
  "Shift",
  "Silk",
  "Silver",
  "Skinny",
  "Sleeveless",
  "Slim",
  "Smock",
  "Snakeskin",
  "Southwestern",
  "Spaghetti Strap",
  "Spandex",
  "Sporty",
  "Spring",
  "Stainproof",
  "Star Wars",
  "Statement Sleeves",
  "Stirrup",
  "Stocking Stuffers",
  "Stoneware",
  "Straight Leg",
  "Strapless",
  "Streetwear",
  "Stretch",
  "Stripes",
  "Suede",
  "Sulfate-Free",
  "Summer",
  "Tailored",
  "Teddy",
  "Tennis Prep",
  "Terracotta",
  "Terrycloth",
  "Tie Dye",
  "Tiger Print",
  "Tik Tok Famous",
  "Toile",
  "Toy Story",
  "Traditional",
  "Travel",
  "Tribal",
  "Tropical",
  "Tunic",
  "Tweed",
  "Two-Tone",
  "Unisex",
  "Upcycled",
  "Utility",
  "Vacation",
  "Valentine's Day",
  "Vegan",
  "Velour",
  "Velvet",
  "Victorian",
  "Vintage",
  "Waterproof",
  "Wedding",
  "Western",
  "Whimsigoth",
  "Wide Leg",
  "Winter",
  "Wood",
  "Wool",
  "Workout",
  "Woven",
  "Y2K",
  "Yoga",
  "Zebra Print",
] as const;

export type PoshmarkStyleTag = (typeof POSHMARK_STYLE_TAGS)[number];

const STYLE_TAG_BY_LOWER = new Map(
  POSHMARK_STYLE_TAGS.map((tag) => [tag.toLowerCase(), tag] as const)
);

/** Map free-text tags onto Poshmark canonical names when possible. */
export function normalizePoshmarkStyleTag(
  raw: string | null | undefined
): string | null {
  if (!raw?.trim()) return null;
  const direct = STYLE_TAG_BY_LOWER.get(raw.trim().toLowerCase());
  return direct ?? null;
}

export function isPoshmarkStyleTag(value: string | null | undefined): boolean {
  return Boolean(value && STYLE_TAG_BY_LOWER.has(value.toLowerCase()));
}

