-- Reseller Assistant initial schema
create extension if not exists "pgcrypto";

create table if not exists workspace (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Household',
  default_smoke_pet_notes text,
  created_at timestamptz not null default now()
);

create table if not exists listings (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspace (id) on delete cascade,
  platform text not null check (platform in ('mercari', 'poshmark')),
  status text not null default 'drafting_photos'
    check (status in ('drafting_photos', 'processing', 'ready', 'posting', 'posted')),
  join_code text not null unique,
  photo_step int not null default 0,
  title text,
  description text,
  price numeric,
  structured_fields jsonb not null default '{}'::jsonb,
  identified_attrs jsonb,
  cover_processed_path text,
  posted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists listing_photos (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references listings (id) on delete cascade,
  role text not null
    check (role in (
      'brand_tag',
      'care_tag',
      'id_tag',
      'inventory',
      'cover',
      'front',
      'back',
      'detail',
      'flaw'
    )),
  storage_path text not null,
  processed_path text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists listing_join_tokens (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references listings (id) on delete cascade,
  token text not null unique,
  purpose text not null check (purpose in ('phone', 'extension')),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists listings_updated_at_idx on listings (updated_at desc);
create index if not exists listing_photos_listing_id_idx on listing_photos (listing_id);
create index if not exists listing_join_tokens_token_idx on listing_join_tokens (token);

insert into workspace (name, default_smoke_pet_notes)
select 'Household', 'From a smoke-free, pet-friendly home.'
where not exists (select 1 from workspace);

-- Storage bucket: create "listing-photos" (private) in the Supabase dashboard
-- and allow service-role uploads. Signed URLs are generated by the app server.
